import type {
  B2BApplication,
  B2BCompany,
  B2BCompanyProfile,
  B2BDocument,
  B2BHistoryEntry,
  B2BProject,
  B2BSolution,
  BusinessType,
} from "./b2b-types";

type ProfileInput = {
  name: string;
  legal: string;
  type: BusinessType;
  city: string;
  country?: string;
  market?: "Türkiye" | "İhracat";
  contact: string;
  role: string;
  scale: string;
};

const profile = (id: number, input: ProfileInput): B2BCompanyProfile => ({
  id,
  companyName: input.name,
  legalName: input.legal,
  taxNumber: `000000${String(id).padStart(4, "0")}`,
  taxOffice: `${input.city} Kurgu Vergi Dairesi`,
  businessType: input.type,
  scaleLabel: input.scale,
  website: `https://firma-${id}.example`,
  phone: `+90 500 100 ${String(id).padStart(2, "0")} 00`,
  email: `yetkili${id}@firma-${id}.example`,
  city: input.city,
  country: input.country ?? "Türkiye",
  contactName: input.contact,
  contactRole: input.role,
  market: input.market ?? "Türkiye",
});

export const b2bProfiles = {
  hotel: profile(1, {
    name: "Lorin Hotel & Spa",
    legal: "Lorin Konaklama A.Ş.",
    type: "Otel",
    city: "Muğla",
    contact: "Deren Aksoy",
    role: "Satın Alma Müdürü",
    scale: "128 oda",
  }),
  restaurant: profile(2, {
    name: "Sera Mutfakları",
    legal: "Sera Restoran İşletmeleri Ltd.",
    type: "Restoran",
    city: "İstanbul",
    contact: "Kaan Ilgaz",
    role: "Operasyon Direktörü",
    scale: "6 şube",
  }),
  cafe: profile(3, {
    name: "Urban Cup",
    legal: "Urban Cup Kahve A.Ş.",
    type: "Kafe",
    city: "İzmir",
    contact: "Lal Ekin",
    role: "Kurucu Ortak",
    scale: "9 şube",
  }),
  office: profile(4, {
    name: "Mesa Workspaces",
    legal: "Mesa Ortak Çalışma Alanları A.Ş.",
    type: "Ofis",
    city: "Ankara",
    contact: "Emir Sönmez",
    role: "İdari İşler Müdürü",
    scale: "420 çalışan",
  }),
  hospital: profile(5, {
    name: "MediNova",
    legal: "MediNova Sağlık Hizmetleri A.Ş.",
    type: "Hastane",
    city: "Bursa",
    contact: "Nisan Acar",
    role: "Tedarik Direktörü",
    scale: "3 hastane",
  }),
  clinic: profile(6, {
    name: "Cura Klinik",
    legal: "Cura Klinik Hizmetleri Ltd.",
    type: "Klinik",
    city: "Antalya",
    contact: "Ozan Berke",
    role: "Klinik Müdürü",
    scale: "4 klinik",
  }),
  school: profile(7, {
    name: "Atlas Eğitim Kampüsleri",
    legal: "Atlas Eğitim Kurumları A.Ş.",
    type: "Okul",
    city: "Ankara",
    contact: "Işıl Baran",
    role: "Satın Alma Uzmanı",
    scale: "5 kampüs",
  }),
  retail: profile(8, {
    name: "Novea Living",
    legal: "Novea Perakende Zinciri A.Ş.",
    type: "Perakende zinciri",
    city: "İstanbul",
    contact: "Meriç Tan",
    role: "Kategori Direktörü",
    scale: "18 mağaza",
  }),
  interior: profile(9, {
    name: "Atelier Kuzey",
    legal: "Atelier Kuzey İç Mimarlık Ltd.",
    type: "İç mimarlık şirketi",
    city: "İstanbul",
    contact: "Ada Yalçın",
    role: "Proje Direktörü",
    scale: "32 çalışan",
  }),
  property: profile(10, {
    name: "Habitat Yaşam Yönetimi",
    legal: "Habitat Site Yönetimi A.Ş.",
    type: "Site/mülk yönetimi",
    city: "Kocaeli",
    contact: "Mert Tuna",
    role: "Tesis Yönetim Müdürü",
    scale: "14 site",
  }),
  distributor: profile(11, {
    name: "Luma Dağıtım",
    legal: "Luma Tüketim Ürünleri Dağıtım A.Ş.",
    type: "Distribütör",
    city: "İzmir",
    contact: "Ece Doruk",
    role: "Genel Müdür",
    scale: "7 bölge deposu",
  }),
  export: profile(12, {
    name: "Arven Global",
    legal: "Arven Global Trading GmbH",
    type: "İhracat iş ortağı",
    city: "Hamburg",
    country: "Almanya",
    market: "İhracat",
    contact: "Mila Arden",
    role: "Partnership Lead",
    scale: "12 ülke",
  }),
};

const documents = (exportCompany = false, missing = false): B2BDocument[] => [
  { name: "Vergi levhası", status: missing ? "Eksik" : "Onaylandı" },
  { name: "Faaliyet belgesi", status: "Yüklendi" },
  { name: "İmza sirküleri", status: missing ? "İnceleniyor" : "Onaylandı" },
  { name: "Yetki belgesi", status: "Yüklendi" },
  { name: "İhracat evrakı", status: exportCompany ? "İnceleniyor" : "Eksik" },
];

const history = (title: string, date: string): B2BHistoryEntry[] => [
  { title, description: "Frontend demo kaydı oluşturuldu.", date },
];

const application = (
  id: number,
  applicationNumber: string,
  profileData: B2BCompanyProfile,
  solutions: B2BSolution[],
  status: B2BApplication["status"],
  date: string,
  manager: B2BApplication["manager"],
  budget: number,
): B2BApplication => ({
  id,
  applicationNumber,
  profile: profileData,
  requestedSolutions: solutions,
  estimatedQuantity: `${120 + id * 80} ürün / ilk faz`,
  estimatedBudget: budget,
  description: `${profileData.companyName}, operasyon ihtiyacına uygun kurumsal ürün ve proje çözümü talep ediyor.`,
  targetDate: `2026-0${Math.min(9, 8 + (id % 2))}-${18 + id}`,
  applicationDate: date,
  approvalDate: status === "Onaylandı" ? "2026-08-08T11:30:00" : undefined,
  manager,
  status,
  documents: documents(
    profileData.market === "İhracat",
    status === "Belge Bekleniyor",
  ),
  notes: [],
  history: history("Başvuru oluşturuldu", date),
  relatedWork: [],
});

export const initialB2BApplications: B2BApplication[] = [
  application(
    1,
    "APP-2026-0418",
    b2bProfiles.hotel,
    ["Hotel Collection", "Toplu Sipariş"],
    "Yeni Başvuru",
    "2026-08-15T09:20:00",
    "Elif Karaca",
    480000,
  ),
  application(
    2,
    "APP-2026-0412",
    b2bProfiles.restaurant,
    ["Restaurant & Cafe", "Private Label/OEM"],
    "İnceleniyor",
    "2026-08-12T14:05:00",
    "Mert Akın",
    260000,
  ),
  application(
    3,
    "APP-2026-0406",
    b2bProfiles.cafe,
    ["Restaurant & Cafe", "Franchise/Bayilik"],
    "Belge Bekleniyor",
    "2026-08-10T10:40:00",
    "Selin Yüce",
    190000,
  ),
  application(
    4,
    "APP-2026-0399",
    b2bProfiles.office,
    ["Office Collection", "Employee Welcome Kits"],
    "Onaylandı",
    "2026-08-07T16:30:00",
    "Can Erdem",
    340000,
  ),
  application(
    5,
    "APP-2026-0387",
    b2bProfiles.clinic,
    ["Healthcare", "Corporate Gifts"],
    "Reddedildi",
    "2026-08-03T11:18:00",
    "Elif Karaca",
    90000,
  ),
  application(
    6,
    "APP-2026-0379",
    b2bProfiles.school,
    ["Toplu Sipariş", "Employee Welcome Kits"],
    "İnceleniyor",
    "2026-07-29T13:42:00",
    "Mert Akın",
    420000,
  ),
  application(
    7,
    "APP-2026-0368",
    b2bProfiles.interior,
    ["Proje Satışı", "Private Label/OEM"],
    "Yeni Başvuru",
    "2026-07-24T15:16:00",
    "Selin Yüce",
    720000,
  ),
];

const company = (
  id: number,
  number: string,
  profileData: B2BCompanyProfile,
  solutions: B2BSolution[],
  status: B2BCompany["status"],
  manager: B2BCompany["manager"],
  revenue: number,
): B2BCompany => ({
  id,
  companyNumber: number,
  profile: profileData,
  activeSolutions: solutions,
  totalOrdersProjects: 3 + id,
  totalRevenue: revenue,
  lastActivityDate: `2026-08-${String(15 - id).padStart(2, "0")}T12:00:00`,
  approvedAt: `2026-0${Math.min(7, 1 + id)}-12T10:00:00`,
  manager,
  status,
  documents: documents(profileData.market === "İhracat"),
  notes: [],
  history: history("Firma iş ortaklığına alındı", "12 Temmuz 2026, 10:00"),
  relatedWork: [
    {
      number: `PRJ-2026-${100 + id}`,
      type: solutions[0],
      createdAt: "2026-08-01T10:00:00",
      amount: revenue / 2,
      status: "Teklif Gönderildi",
    },
  ],
});

export const initialB2BCompanies: B2BCompany[] = [
  {
    ...company(
      1,
      "B2B-2026-0218",
      b2bProfiles.office,
      ["Office Collection", "Employee Welcome Kits"],
      "Aktif",
      "Can Erdem",
      890000,
    ),
    sourceApplicationNumber: "APP-2026-0399",
  },
  company(
    2,
    "B2B-2026-0204",
    b2bProfiles.hospital,
    ["Healthcare", "Toplu Sipariş"],
    "Aktif",
    "Elif Karaca",
    1480000,
  ),
  company(
    3,
    "B2B-2026-0191",
    b2bProfiles.retail,
    ["Private Label/OEM", "Franchise/Bayilik"],
    "Aktif",
    "Mert Akın",
    2350000,
  ),
  company(
    4,
    "B2B-2026-0177",
    b2bProfiles.property,
    ["Toplu Sipariş", "Proje Satışı"],
    "Askıda",
    "Selin Yüce",
    610000,
  ),
  company(
    5,
    "B2B-2026-0168",
    b2bProfiles.distributor,
    ["Distribütörlük", "Private Label/OEM"],
    "Aktif",
    "Mert Akın",
    3180000,
  ),
  company(
    6,
    "B2B-2026-0153",
    b2bProfiles.export,
    ["İhracat", "Distribütörlük"],
    "Aktif",
    "Elif Karaca",
    4260000,
  ),
  company(
    7,
    "B2B-2026-0142",
    b2bProfiles.hotel,
    ["Hotel Collection", "Corporate Gifts"],
    "Pasif",
    "Can Erdem",
    770000,
  ),
  company(
    8,
    "B2B-2026-0136",
    b2bProfiles.restaurant,
    ["Restaurant & Cafe", "Toplu Sipariş"],
    "Aktif",
    "Selin Yüce",
    980000,
  ),
];

const project = (
  id: number,
  number: string,
  profileData: B2BCompanyProfile,
  solution: B2BSolution,
  status: B2BProject["status"],
  manager: B2BProject["manager"],
  budget: number,
): B2BProject => ({
  id,
  projectNumber: number,
  profile: profileData,
  solution,
  summary: `${profileData.companyName} için ${solution} kapsamlı kurumsal çözüm çalışması.`,
  estimatedBudget: budget,
  createdAt: `2026-08-${String(15 - id).padStart(2, "0")}T09:30:00`,
  targetDate: `2026-09-${String(10 + id).padStart(2, "0")}T17:00:00`,
  manager,
  status,
  documents: documents(profileData.market === "İhracat"),
  notes: [],
  history: history(
    "Talep/proje oluşturuldu",
    `2026-08-${String(15 - id).padStart(2, "0")}T09:30:00`,
  ),
  relatedWork: [
    {
      number,
      type: solution,
      createdAt: `2026-08-${String(15 - id).padStart(2, "0")}T09:30:00`,
      amount: budget,
      status,
    },
  ],
});

export const initialB2BProjects: B2BProject[] = [
  project(
    1,
    "PRJ-2026-0188",
    b2bProfiles.hospital,
    "Healthcare",
    "Teklif Hazırlanıyor",
    "Elif Karaca",
    620000,
  ),
  project(
    2,
    "REQ-2026-0274",
    b2bProfiles.retail,
    "Private Label/OEM",
    "Yeni Talep",
    "Mert Akın",
    880000,
  ),
  project(
    3,
    "PRJ-2026-0181",
    b2bProfiles.export,
    "İhracat",
    "Teklif Gönderildi",
    "Elif Karaca",
    1450000,
  ),
  project(
    4,
    "REQ-2026-0263",
    b2bProfiles.property,
    "Proje Satışı",
    "Görüşme Planlandı",
    "Selin Yüce",
    310000,
  ),
  project(
    5,
    "PRJ-2026-0172",
    b2bProfiles.office,
    "Employee Welcome Kits",
    "Onaylandı",
    "Can Erdem",
    275000,
  ),
  project(
    6,
    "PRJ-2026-0164",
    b2bProfiles.restaurant,
    "Restaurant & Cafe",
    "Tamamlandı",
    "Selin Yüce",
    430000,
  ),
  project(
    7,
    "REQ-2026-0249",
    b2bProfiles.distributor,
    "Distribütörlük",
    "Teklif Hazırlanıyor",
    "Mert Akın",
    920000,
  ),
  project(
    8,
    "PRJ-2026-0151",
    b2bProfiles.hotel,
    "Hotel Collection",
    "İptal Edildi",
    "Can Erdem",
    510000,
  ),
  project(
    9,
    "REQ-2026-0238",
    b2bProfiles.interior,
    "Corporate Gifts",
    "Yeni Talep",
    "Elif Karaca",
    180000,
  ),
];
