import type { AdminProduct } from "./product-types";

export { productCategories } from "./product-types";
export type {
  AdminProduct,
  ProductCategory,
  ProductStatus,
} from "./product-types";

export const mockProducts: AdminProduct[] = [
  {
    id: 1,
    name: "Banyo Kokusu Seti",
    sku: "SOF-BNY-1042",
    category: "Banyo",
    b2cPrice: 749.9,
    b2bPrice: 524.9,
    stock: 5,
    minimumStock: 10,
    status: "Aktif",
    visual: "BK",
    visualTone: "rose",
  },
  {
    id: 2,
    name: "Yüz Havlusu – Bej",
    sku: "SOF-BNY-1088",
    category: "Banyo",
    b2cPrice: 289.9,
    b2bPrice: 199.9,
    stock: 38,
    minimumStock: 12,
    status: "Aktif",
    visual: "YH",
    visualTone: "sand",
  },
  {
    id: 3,
    name: "Seramik Sabunluk",
    sku: "SOF-BNY-1126",
    category: "Banyo",
    b2cPrice: 349.9,
    b2bPrice: 239.9,
    stock: 0,
    minimumStock: 8,
    status: "Pasif",
    visual: "SS",
    visualTone: "lavender",
  },
  {
    id: 4,
    name: "Limon Bulaşık Deterjanı",
    sku: "SOF-MTF-2041",
    category: "Mutfak",
    b2cPrice: 189.9,
    b2bPrice: 129.9,
    stock: 64,
    minimumStock: 20,
    status: "Aktif",
    visual: "LD",
    visualTone: "peach",
  },
  {
    id: 5,
    name: "Pamuklu Nevresim Takımı",
    sku: "SOF-UYK-3014",
    category: "Uyku",
    b2cPrice: 2199.9,
    b2bPrice: 1599.9,
    stock: 9,
    minimumStock: 10,
    status: "Aktif",
    visual: "PN",
    visualTone: "lavender",
  },
  {
    id: 6,
    name: "Ahşap Servis Tepsisi",
    sku: "SOF-MTF-2097",
    category: "Mutfak",
    b2cPrice: 679.9,
    b2bPrice: 469.9,
    stock: 24,
    minimumStock: 10,
    status: "Pasif",
    visual: "AT",
    visualTone: "sand",
  },
  {
    id: 7,
    name: "Evcil Dostlar Bakım Seti",
    sku: "SOF-EVC-4018",
    category: "Evcil Dostlar",
    b2cPrice: 899.9,
    b2bPrice: 629.9,
    stock: 7,
    minimumStock: 10,
    status: "Aktif",
    visual: "EB",
    visualTone: "mint",
  },
  {
    id: 8,
    name: "Lavanta Oda Kokusu",
    sku: "SOF-EVB-5033",
    category: "Ev Bakımı",
    b2cPrice: 429.9,
    b2bPrice: 299.9,
    stock: 42,
    minimumStock: 15,
    status: "Aktif",
    visual: "LO",
    visualTone: "rose",
  },
];
