import type { AdminPayment } from "./payment-types";

export const mockPayments: AdminPayment[] = [
  {
    id: 1,
    transactionNumber: "PAY-2026-87421",
    orderNumber: "#SOF-2026-1284",
    customerName: "Ayşe Yılmaz",
    customerType: "B2C",
    salesChannel: "Web sitesi",
    salesLocation: "Türkiye · İstanbul",
    paymentDate: "2026-08-11T12:19:00",
    paymentDateLabel: "11 Ağustos 2026, 12:19",
    paymentMethod: "Kredi/banka kartı",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "TRY",
    subtotal: 2629.8,
    discount: 179.8,
    shipping: 0,
    amount: 2450,
    reportingAmountTry: 2450,
    paymentStatus: "Başarılı",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EAR202600001284",
    invoiceDate: "11 Ağustos 2026, 12:24",
    invoiceType: "E-Arşiv",
    orderItems: [
      { name: "Pamuklu Nevresim Takımı", sku: "SOF-UYK-3014", quantity: 1 },
      { name: "Lavanta Oda Kokusu", sku: "SOF-EVB-5033", quantity: 1 },
    ],
    timeline: [
      {
        title: "Ödeme başlatıldı",
        date: "11 Ağustos 2026, 12:18",
        description: "Ödeme talebi güvenli ödeme altyapısına iletildi.",
      },
      {
        title: "Ödeme onaylandı",
        date: "11 Ağustos 2026, 12:19",
        description: "Tahsilat başarılı olarak sonuçlandı.",
      },
      {
        title: "E-arşiv faturası oluşturuldu",
        date: "11 Ağustos 2026, 12:24",
        description: "Mock fatura numarası ödeme kaydına bağlandı.",
      },
    ],
  },
  {
    id: 2,
    transactionNumber: "PAY-2026-87418",
    orderNumber: "#SOF-2026-1283",
    customerName: "Mehmet Demir",
    customerType: "B2C",
    salesChannel: "Web sitesi",
    salesLocation: "Türkiye · Ankara",
    paymentDate: "2026-08-11T10:37:00",
    paymentDateLabel: "11 Ağustos 2026, 10:37",
    paymentMethod: "Kredi/banka kartı",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "TRY",
    subtotal: 1849.7,
    discount: 0,
    shipping: 40.3,
    amount: 1890,
    reportingAmountTry: 1890,
    paymentStatus: "Başarılı",
    invoiceStatus: "Fatura Bekliyor",
    invoiceType: "E-Arşiv",
    orderItems: [
      { name: "Banyo Kokusu Seti", sku: "SOF-BNY-1042", quantity: 2 },
      { name: "Seramik Sabunluk", sku: "SOF-BNY-1126", quantity: 1 },
    ],
    timeline: [
      {
        title: "Ödeme başlatıldı",
        date: "11 Ağustos 2026, 10:36",
        description: "Kart doğrulaması başlatıldı.",
      },
      {
        title: "Ödeme onaylandı",
        date: "11 Ağustos 2026, 10:37",
        description: "Tahsilat başarılı olarak tamamlandı.",
      },
      {
        title: "Fatura sıraya alındı",
        date: "11 Ağustos 2026, 10:38",
        description: "E-arşiv faturası mock oluşturma sırasında bekliyor.",
      },
    ],
  },
  {
    id: 3,
    transactionNumber: "B2B-TRX-0942",
    orderNumber: "#SOF-B2B-0942",
    customerName: "Selin Aksoy",
    companyName: "Minoa Hotel & Spa A.Ş.",
    customerType: "B2B",
    salesChannel: "Web sitesi",
    salesLocation: "Türkiye · İstanbul",
    paymentDate: "2026-08-10T16:25:00",
    paymentDateLabel: "10 Ağustos 2026, 16:25",
    paymentMethod: "B2B banka transferi",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "TRY",
    subtotal: 7947,
    discount: 397.35,
    shipping: 0,
    amount: 7549.65,
    reportingAmountTry: 7549.65,
    paymentStatus: "Bekliyor",
    invoiceStatus: "Fatura Bekliyor",
    invoiceType: "E-Arşiv",
    orderItems: [
      { name: "Yüz Havlusu – Bej", sku: "SOF-BNY-1088", quantity: 24 },
      { name: "Banyo Kokusu Seti", sku: "SOF-BNY-1042", quantity: 6 },
    ],
    timeline: [
      {
        title: "Kurumsal ödeme kaydı açıldı",
        date: "10 Ağustos 2026, 16:25",
        description: "B2B banka transferi için tahsilat kaydı oluşturuldu.",
      },
      {
        title: "Banka transferi bekleniyor",
        date: "10 Ağustos 2026, 16:26",
        description: "Ödeme henüz hesap hareketleriyle eşleşmedi.",
      },
    ],
  },
  {
    id: 4,
    transactionNumber: "MKT-2026-55291",
    orderNumber: "#SOF-MKT-4621",
    customerName: "Zeynep Kaya",
    customerType: "B2C",
    salesChannel: "Pazaryeri",
    salesLocation: "Trendyol · İzmir",
    paymentDate: "2026-08-10T14:07:00",
    paymentDateLabel: "10 Ağustos 2026, 14:07",
    paymentMethod: "Pazaryeri ödemesi",
    paymentProvider: "Pazaryeri ödeme altyapısı",
    currency: "TRY",
    subtotal: 3559.7,
    discount: 0,
    shipping: 0,
    amount: 3559.7,
    reportingAmountTry: 3559.7,
    paymentStatus: "Başarılı",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EAR202600004621",
    invoiceDate: "10 Ağustos 2026, 14:15",
    invoiceType: "E-Arşiv",
    orderItems: [
      { name: "Pamuklu Nevresim Takımı", sku: "SOF-UYK-3014", quantity: 1 },
      { name: "Ahşap Servis Tepsisi", sku: "SOF-MTF-2097", quantity: 2 },
    ],
    timeline: [
      {
        title: "Pazaryeri ödemesi aktarıldı",
        date: "10 Ağustos 2026, 14:07",
        description: "Pazaryeri siparişinin ödeme bilgisi içe aktarıldı.",
      },
      {
        title: "E-arşiv faturası oluşturuldu",
        date: "10 Ağustos 2026, 14:15",
        description: "Mock fatura bilgisi kaydedildi.",
      },
    ],
  },
  {
    id: 5,
    transactionNumber: "EXP-2026-01882",
    orderNumber: "#SOF-EXP-01882",
    customerName: "Sophie Martin",
    customerType: "B2C",
    salesChannel: "E-ihracat",
    salesLocation: "Fransa · Paris",
    paymentDate: "2026-08-09T13:42:00",
    paymentDateLabel: "9 Ağustos 2026, 13:42",
    paymentMethod: "Kredi/banka kartı",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "EUR",
    subtotal: 132,
    discount: 12,
    shipping: 15,
    amount: 135,
    reportingAmountTry: 6473.25,
    paymentStatus: "Başarılı",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EIH202600001882",
    invoiceDate: "9 Ağustos 2026, 13:50",
    invoiceType: "E-İhracat",
    orderItems: [
      { name: "Pamuklu Nevresim Takımı", sku: "SOF-UYK-3014", quantity: 1 },
      { name: "Lavanta Oda Kokusu", sku: "SOF-EVB-5033", quantity: 2 },
    ],
    timeline: [
      {
        title: "Dövizli ödeme başlatıldı",
        date: "9 Ağustos 2026, 13:41",
        description: "EUR ödeme talebi genel sağlayıcıya iletildi.",
      },
      {
        title: "Ödeme onaylandı",
        date: "9 Ağustos 2026, 13:42",
        description: "E-ihracat tahsilatı başarıyla tamamlandı.",
      },
      {
        title: "E-ihracat faturası oluşturuldu",
        date: "9 Ağustos 2026, 13:50",
        description: "Mock e-ihracat fatura bilgisi kaydedildi.",
      },
    ],
  },
  {
    id: 6,
    transactionNumber: "PAY-2026-87374",
    orderNumber: "#SOF-2026-1279",
    customerName: "Emre Arslan",
    customerType: "B2C",
    salesChannel: "Web sitesi",
    salesLocation: "Türkiye · Samsun",
    paymentDate: "2026-08-08T17:34:00",
    paymentDateLabel: "8 Ağustos 2026, 17:34",
    paymentMethod: "Kredi/banka kartı",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "TRY",
    subtotal: 899.9,
    discount: 0,
    shipping: 49.9,
    amount: 949.8,
    reportingAmountTry: 949.8,
    paymentStatus: "İade Edildi",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EAR202600001279",
    invoiceDate: "8 Ağustos 2026, 17:41",
    invoiceType: "E-Arşiv",
    refundAmount: 949.8,
    refundReportingAmountTry: 949.8,
    refundDate: "8 Ağustos 2026, 18:12",
    orderItems: [
      { name: "Evcil Dostlar Bakım Seti", sku: "SOF-EVC-4018", quantity: 1 },
    ],
    timeline: [
      {
        title: "Ödeme onaylandı",
        date: "8 Ağustos 2026, 17:34",
        description: "Kart tahsilatı başarıyla tamamlandı.",
      },
      {
        title: "E-arşiv faturası oluşturuldu",
        date: "8 Ağustos 2026, 17:41",
        description: "Mock e-arşiv fatura bilgisi oluşturuldu.",
      },
      {
        title: "Tam iade kaydedildi",
        date: "8 Ağustos 2026, 18:12",
        description: "Ödemenin tamamı için geçmiş iade bilgisi kaydedildi.",
      },
    ],
  },
  {
    id: 7,
    transactionNumber: "MKT-2026-55108",
    orderNumber: "#SOF-MKT-4587",
    customerName: "Fatma Çelik",
    customerType: "B2C",
    salesChannel: "Pazaryeri",
    salesLocation: "Hepsiburada · Eskişehir",
    paymentDate: "2026-08-07T13:12:00",
    paymentDateLabel: "7 Ağustos 2026, 13:12",
    paymentMethod: "Pazaryeri ödemesi",
    paymentProvider: "Pazaryeri ödeme altyapısı",
    currency: "TRY",
    subtotal: 1059.7,
    discount: 149.7,
    shipping: 40,
    amount: 950,
    reportingAmountTry: 950,
    paymentStatus: "Kısmi İade",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EAR202600004587",
    invoiceDate: "7 Ağustos 2026, 13:20",
    invoiceType: "E-Arşiv",
    refundAmount: 189.9,
    refundReportingAmountTry: 189.9,
    refundDate: "9 Ağustos 2026, 09:16",
    orderItems: [
      { name: "Ahşap Servis Tepsisi", sku: "SOF-MTF-2097", quantity: 1 },
      { name: "Limon Bulaşık Deterjanı", sku: "SOF-MTF-2041", quantity: 2 },
    ],
    timeline: [
      {
        title: "Pazaryeri ödemesi alındı",
        date: "7 Ağustos 2026, 13:12",
        description: "Pazaryeri tahsilat bilgisi kaydedildi.",
      },
      {
        title: "Kısmi iade kaydedildi",
        date: "9 Ağustos 2026, 09:16",
        description: "Bir ürün için geçmiş iade bilgisi işlendi.",
      },
    ],
  },
  {
    id: 8,
    transactionNumber: "EXP-2026-01863",
    orderNumber: "#SOF-EXP-01863",
    customerName: "Oliver Smith",
    customerType: "B2C",
    salesChannel: "E-ihracat",
    salesLocation: "Birleşik Krallık · Londra",
    paymentDate: "2026-08-06T09:48:00",
    paymentDateLabel: "6 Ağustos 2026, 09:48",
    paymentMethod: "Kredi/banka kartı",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "GBP",
    subtotal: 89,
    discount: 0,
    shipping: 12,
    amount: 101,
    reportingAmountTry: 5631.76,
    paymentStatus: "Başarısız",
    invoiceStatus: "Fatura Gerekmiyor",
    invoiceType: "Gerekmiyor",
    orderItems: [
      { name: "Banyo Kokusu Seti", sku: "SOF-BNY-1042", quantity: 1 },
    ],
    timeline: [
      {
        title: "Ödeme başlatıldı",
        date: "6 Ağustos 2026, 09:47",
        description: "GBP ödeme talebi sağlayıcıya iletildi.",
      },
      {
        title: "Ödeme başarısız",
        date: "6 Ağustos 2026, 09:48",
        description: "Ödeme sağlayıcısından başarısız sonucu alındı.",
      },
    ],
  },
  {
    id: 9,
    transactionNumber: "B2B-TRX-0935",
    orderNumber: "#SOF-B2B-0935",
    customerName: "Tolga Erdem",
    companyName: "Arca Residence İşletmeleri",
    customerType: "B2B",
    salesChannel: "Web sitesi",
    salesLocation: "Türkiye · İzmir",
    paymentDate: "2026-08-03T10:18:00",
    paymentDateLabel: "3 Ağustos 2026, 10:18",
    paymentMethod: "B2B banka transferi",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "TRY",
    subtotal: 21996,
    discount: 1996,
    shipping: 0,
    amount: 20000,
    reportingAmountTry: 20000,
    paymentStatus: "Başarılı",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EAR202600000935",
    invoiceDate: "3 Ağustos 2026, 10:36",
    invoiceType: "E-Arşiv",
    orderItems: [
      { name: "Pamuklu Nevresim Takımı", sku: "SOF-UYK-3014", quantity: 10 },
      { name: "Yüz Havlusu – Bej", sku: "SOF-BNY-1088", quantity: 30 },
    ],
    timeline: [
      {
        title: "Banka transferi eşleşti",
        date: "3 Ağustos 2026, 10:18",
        description: "Kurumsal ödeme sipariş kaydıyla eşleştirildi.",
      },
      {
        title: "Fatura oluşturuldu",
        date: "3 Ağustos 2026, 10:36",
        description: "Mock kurumsal e-arşiv faturası oluşturuldu.",
      },
    ],
  },
  {
    id: 10,
    transactionNumber: "PAY-2026-87142",
    orderNumber: "#SOF-2026-1268",
    customerName: "Gökçe Şahin",
    customerType: "B2C",
    salesChannel: "Web sitesi",
    salesLocation: "Türkiye · Muğla",
    paymentDate: "2026-08-01T18:41:00",
    paymentDateLabel: "1 Ağustos 2026, 18:41",
    paymentMethod: "Havale/EFT",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "TRY",
    subtotal: 749.9,
    discount: 0,
    shipping: 49.9,
    amount: 799.8,
    reportingAmountTry: 799.8,
    paymentStatus: "Bekliyor",
    invoiceStatus: "Fatura Bekliyor",
    invoiceType: "E-Arşiv",
    orderItems: [
      { name: "Banyo Kokusu Seti", sku: "SOF-BNY-1042", quantity: 1 },
    ],
    timeline: [
      {
        title: "Havale talimatı oluşturuldu",
        date: "1 Ağustos 2026, 18:41",
        description: "Ödeme referansı müşteriye gösterildi.",
      },
      {
        title: "Tahsilat bekleniyor",
        date: "1 Ağustos 2026, 18:42",
        description: "Banka hareketi henüz ödeme kaydıyla eşleşmedi.",
      },
    ],
  },
  {
    id: 11,
    transactionNumber: "EXP-2026-01794",
    orderNumber: "#SOF-EXP-01794",
    customerName: "Anna Keller",
    companyName: "Nordlicht Home GmbH",
    customerType: "B2B",
    salesChannel: "E-ihracat",
    salesLocation: "Almanya · Hamburg",
    paymentDate: "2026-07-29T11:22:00",
    paymentDateLabel: "29 Temmuz 2026, 11:22",
    paymentMethod: "B2B banka transferi",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "EUR",
    subtotal: 1380,
    discount: 80,
    shipping: 120,
    amount: 1420,
    reportingAmountTry: 68082.2,
    paymentStatus: "Başarılı",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EIH202600001794",
    invoiceDate: "29 Temmuz 2026, 11:40",
    invoiceType: "E-İhracat",
    orderItems: [
      { name: "Yüz Havlusu – Bej", sku: "SOF-BNY-1088", quantity: 40 },
      { name: "Banyo Kokusu Seti", sku: "SOF-BNY-1042", quantity: 12 },
    ],
    timeline: [
      {
        title: "Uluslararası transfer eşleşti",
        date: "29 Temmuz 2026, 11:22",
        description: "EUR banka transferi kurumsal siparişle eşleştirildi.",
      },
      {
        title: "E-ihracat faturası oluşturuldu",
        date: "29 Temmuz 2026, 11:40",
        description: "Mock fatura kaydı ödeme işlemine bağlandı.",
      },
    ],
  },
  {
    id: 12,
    transactionNumber: "MKT-2026-54831",
    orderNumber: "#SOF-MKT-4512",
    customerName: "Deniz Aydın",
    customerType: "B2C",
    salesChannel: "Pazaryeri",
    salesLocation: "Amazon Türkiye · Antalya",
    paymentDate: "2026-07-26T15:30:00",
    paymentDateLabel: "26 Temmuz 2026, 15:30",
    paymentMethod: "Pazaryeri ödemesi",
    paymentProvider: "Pazaryeri ödeme altyapısı",
    currency: "TRY",
    subtotal: 1159.6,
    discount: 59.6,
    shipping: 0,
    amount: 1100,
    reportingAmountTry: 1100,
    paymentStatus: "Başarısız",
    invoiceStatus: "Fatura Gerekmiyor",
    invoiceType: "Gerekmiyor",
    orderItems: [
      { name: "Yüz Havlusu – Bej", sku: "SOF-BNY-1088", quantity: 4 },
    ],
    timeline: [
      {
        title: "Pazaryeri ödeme kaydı alındı",
        date: "26 Temmuz 2026, 15:30",
        description: "Başarısız ödeme sonucu pazaryerinden içe aktarıldı.",
      },
    ],
  },
  {
    id: 13,
    transactionNumber: "PAY-2026-86984",
    orderNumber: "#SOF-2026-1254",
    customerName: "Ceren Koç",
    customerType: "B2C",
    salesChannel: "Web sitesi",
    salesLocation: "Türkiye · Ankara",
    paymentDate: "2026-07-22T09:14:00",
    paymentDateLabel: "22 Temmuz 2026, 09:14",
    paymentMethod: "Havale/EFT",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "TRY",
    subtotal: 1289.7,
    discount: 89.7,
    shipping: 0,
    amount: 1200,
    reportingAmountTry: 1200,
    paymentStatus: "Başarılı",
    invoiceStatus: "Fatura Hatası",
    invoiceType: "E-Arşiv",
    orderItems: [
      { name: "Lavanta Oda Kokusu", sku: "SOF-EVB-5033", quantity: 3 },
    ],
    timeline: [
      {
        title: "Havale eşleşti",
        date: "22 Temmuz 2026, 09:14",
        description: "Ödeme başarıyla siparişe bağlandı.",
      },
      {
        title: "Fatura entegrasyonu hata verdi",
        date: "22 Temmuz 2026, 09:19",
        description: "Mock fatura servisinden hata durumu alındı.",
      },
    ],
  },
  {
    id: 14,
    transactionNumber: "EXP-2026-01721",
    orderNumber: "#SOF-EXP-01721",
    customerName: "Marco Rossi",
    customerType: "B2C",
    salesChannel: "E-ihracat",
    salesLocation: "İtalya · Milano",
    paymentDate: "2026-07-18T17:06:00",
    paymentDateLabel: "18 Temmuz 2026, 17:06",
    paymentMethod: "Kredi/banka kartı",
    paymentProvider: "Genel ödeme altyapısı",
    currency: "USD",
    subtotal: 104,
    discount: 4,
    shipping: 18,
    amount: 118,
    reportingAmountTry: 4873.4,
    paymentStatus: "Kısmi İade",
    invoiceStatus: "Fatura Oluşturuldu",
    invoiceNumber: "EIH202600001721",
    invoiceDate: "18 Temmuz 2026, 17:16",
    invoiceType: "E-İhracat",
    refundAmount: 28,
    refundReportingAmountTry: 1156.4,
    refundDate: "21 Temmuz 2026, 10:08",
    orderItems: [
      { name: "Banyo Kokusu Seti", sku: "SOF-BNY-1042", quantity: 1 },
      { name: "Lavanta Oda Kokusu", sku: "SOF-EVB-5033", quantity: 1 },
    ],
    timeline: [
      {
        title: "USD ödeme onaylandı",
        date: "18 Temmuz 2026, 17:06",
        description: "E-ihracat tahsilatı başarıyla sonuçlandı.",
      },
      {
        title: "E-ihracat faturası oluşturuldu",
        date: "18 Temmuz 2026, 17:16",
        description: "Mock e-ihracat faturası kaydedildi.",
      },
      {
        title: "Kısmi iade kaydedildi",
        date: "21 Temmuz 2026, 10:08",
        description: "Geçmiş kısmi iade bilgisi ödeme kaydına işlendi.",
      },
    ],
  },
];
