import type { Insight, ReviewTheme } from "./insight-types";

const history = (title: string, date: string) => [
  { title: "İçgörü oluşturuldu", description: title, date },
];
const base: Pick<Insight, "notes" | "cautions" | "targetDuration"> = {
  notes: [],
  cautions: ["Sonuçlar dönemsel talep değişimlerinden etkilenebilir."],
  targetDuration: "14 gün",
};

export const initialInsights: Insight[] = [
  {
    ...base,
    id: 1,
    title: "Banyo Kokusu Seti stok tükenme riski",
    description:
      "Satış ivmesi mevcut stok yenileme hızının üzerine çıktı; stok kaybı yaşanabilir.",
    source: "Stok",
    type: "Risk",
    priority: "Kritik",
    status: "Yeni",
    detectedAt: "2026-08-15T10:20:00+03:00",
    channel: "Tüm kanallar",
    affectedArea: "Banyo Kokusu Seti",
    metricLabel: "Kalan stok süresi",
    metricValue: "6 gün",
    changePercent: -42,
    trendImpact: "negative",
    financialImpact: 184000,
    periodComparison: "Son 7 gün / önceki 7 gün",
    recommendation:
      "Tedarik planını öne alın ve kanal bazlı güvenli stok sınırı uygulayın.",
    expectedImpact:
      "Tahmini satış kaybının azaltılması ve ürün bulunurluğunun korunması.",
    suggestedTeam: "Tedarik ve Stok",
    evidence: [
      {
        label: "Günlük satış",
        previous: "18 adet",
        current: "31 adet",
        change: "+%72",
      },
      {
        label: "Mevcut stok",
        previous: "284 adet",
        current: "176 adet",
        change: "-%38",
      },
    ],
    rationale:
      "Satış hızı %72 artarken stok seviyesi %38 düştüğü için altı gün içinde tükenme olasılığı yükseldi.",
    history: history(
      "Satış ve stok eğilimi eşleştirildi.",
      "15 Ağustos 2026 10:20",
    ),
  },
  {
    ...base,
    id: 2,
    title: "Seramik Sabunluk iade oranında yükseliş",
    description:
      "İade oranı benzer ürünlerin ortalamasının belirgin biçimde üzerine çıktı.",
    source: "İade ve iptaller",
    type: "Anomali",
    priority: "Yüksek",
    status: "İnceleniyor",
    detectedAt: "2026-08-14T13:00:00+03:00",
    channel: "Web sitesi",
    affectedArea: "Seramik Sabunluk",
    metricLabel: "İade oranı",
    metricValue: "%8,4",
    changePercent: 61,
    trendImpact: "negative",
    financialImpact: 73500,
    periodComparison: "Son 30 gün / önceki 30 gün",
    recommendation:
      "Hasar nedenlerini paketleme ve kargo kırılımında inceleyin.",
    expectedImpact:
      "İade maliyetinde ve olumsuz müşteri deneyiminde düşüş olabilir.",
    suggestedTeam: "Ürün Geliştirme",
    evidence: [
      {
        label: "İade oranı",
        previous: "%5,2",
        current: "%8,4",
        change: "+%61",
      },
      {
        label: "Hasarlı ürün bildirimi",
        previous: "17",
        current: "31",
        change: "+%82",
      },
    ],
    rationale: "İade artışının çoğu hasarlı teslimat gerekçesiyle eşleşiyor.",
    history: history(
      "İade eğilimi kategori ortalamasıyla karşılaştırıldı.",
      "14 Ağustos 2026 13:00",
    ),
  },
  {
    ...base,
    id: 3,
    title: "Ambalaj dayanıklılığı tekrar eden müşteri sorunu",
    description:
      "Yorumlarda kutu deformasyonu ve koruma yetersizliği tekrar ediyor.",
    source: "Müşteri yorumları/Review Lab",
    type: "Müşteri Sorunu",
    priority: "Yüksek",
    status: "Aksiyon Planlandı",
    detectedAt: "2026-08-13T11:15:00+03:00",
    channel: "Pazaryeri",
    affectedArea: "Banyo ve mutfak kategorileri",
    metricLabel: "Olumsuz yorum",
    metricValue: "46 yorum",
    changePercent: 35,
    trendImpact: "negative",
    financialImpact: 52000,
    periodComparison: "Son 30 gün / önceki 30 gün",
    recommendation: "Köşe koruyucu ve darbe emici iç ambalaj pilotu başlatın.",
    expectedImpact:
      "Hasar odaklı yorumların ve iadelerin azalması beklenebilir.",
    suggestedTeam: "Ürün Geliştirme",
    targetDuration: "21 gün",
    evidence: [
      {
        label: "Ambalaj şikâyeti",
        previous: "34 yorum",
        current: "46 yorum",
        change: "+%35",
      },
      {
        label: "Olumsuz eğilim",
        previous: "%18",
        current: "%27",
        change: "+9 puan",
      },
    ],
    rationale:
      "Farklı ürünlerde aynı ambalaj teması tekrar ettiği için ortak iyileştirme alanı oluştu.",
    actionPlan: {
      team: "Ürün Geliştirme",
      targetDate: "2026-09-05",
      description: "Yeni koruyucu ambalajla 100 siparişlik pilot uygulama.",
    },
    history: [
      ...history("Yorum temaları gruplandı.", "13 Ağustos 2026 11:15"),
      {
        title: "Aksiyon planlandı",
        description: "Ambalaj pilotu tanımlandı.",
        date: "14 Ağustos 2026 09:30",
      },
    ],
  },
  {
    ...base,
    id: 4,
    title: "Pazaryeri dönüşüm oranında gerileme",
    description:
      "Ürün görüntülenmesi artmasına rağmen sepete ekleme ve satın alma oranı düştü.",
    source: "Pazaryerleri",
    type: "Risk",
    priority: "Yüksek",
    status: "Yeni",
    detectedAt: "2026-08-12T16:40:00+03:00",
    channel: "Pazaryeri",
    affectedArea: "Hepsiburada mağazası",
    metricLabel: "Dönüşüm oranı",
    metricValue: "%2,1",
    changePercent: -29,
    trendImpact: "negative",
    financialImpact: 126000,
    periodComparison: "Son 30 gün / önceki 30 gün",
    recommendation:
      "İlk görsel, fiyat konumu ve teslimat vaadini kategori rakipleriyle karşılaştırın.",
    expectedImpact: "Dönüşüm oranında toparlanma fırsatı olabilir.",
    suggestedTeam: "Pazarlama",
    evidence: [
      { label: "Dönüşüm", previous: "%2,95", current: "%2,1", change: "-%29" },
      {
        label: "Görüntülenme",
        previous: "84 bin",
        current: "96 bin",
        change: "+%14",
      },
    ],
    rationale:
      "Trafik artarken dönüşüm düşmesi ürün sayfası veya teklif kalitesi sorununa işaret ediyor.",
    history: history(
      "Pazaryeri hunisi karşılaştırıldı.",
      "12 Ağustos 2026 16:40",
    ),
  },
  {
    ...base,
    id: 5,
    title: "VIP segmentinde tekrar alışveriş azalıyor",
    description:
      "VIP müşterilerin ikinci ve sonraki sipariş sıklığı önceki dönemin altında kaldı.",
    source: "Müşteriler",
    type: "Risk",
    priority: "Orta",
    status: "İnceleniyor",
    detectedAt: "2026-08-10T09:25:00+03:00",
    channel: "Web sitesi",
    affectedArea: "VIP Müşteri segmenti",
    metricLabel: "Tekrar alışveriş",
    metricValue: "%38",
    changePercent: -18,
    trendImpact: "negative",
    financialImpact: 97000,
    periodComparison: "Son 90 gün / önceki 90 gün",
    recommendation:
      "VIP müşteriler için kişiselleştirilmiş kategori önerisi ve sadakat avantajı deneyin.",
    expectedImpact: "Tekrar alışveriş oranında artış fırsatı olabilir.",
    suggestedTeam: "Müşteri Deneyimi",
    evidence: [
      {
        label: "Tekrar alışveriş",
        previous: "%46",
        current: "%38",
        change: "-%18",
      },
      {
        label: "Sipariş aralığı",
        previous: "41 gün",
        current: "54 gün",
        change: "+13 gün",
      },
    ],
    rationale: "Hem tekrar oranı geriledi hem de siparişler arası süre uzadı.",
    history: history(
      "VIP kohortları karşılaştırıldı.",
      "10 Ağustos 2026 09:25",
    ),
  },
  {
    ...base,
    id: 6,
    title: "Otel müşterilerinde toplu sipariş fırsatı",
    description:
      "B2B otel başvurularında Hotel Collection ve toplu sipariş talebi birlikte artıyor.",
    source: "B2B başvuruları",
    type: "Fırsat",
    priority: "Yüksek",
    status: "Yeni",
    detectedAt: "2026-08-09T14:10:00+03:00",
    channel: "B2B",
    affectedArea: "Otel segmenti",
    metricLabel: "Nitelikli talep",
    metricValue: "14 başvuru",
    changePercent: 56,
    trendImpact: "positive",
    financialImpact: 420000,
    periodComparison: "Son 30 gün / önceki 30 gün",
    recommendation:
      "Otel segmentine özel hazır teklif paketi ve örnek ürün seti oluşturun.",
    expectedImpact:
      "Teklif hazırlama süresi kısalabilir ve dönüşüm fırsatı artabilir.",
    suggestedTeam: "B2B Satış",
    evidence: [
      {
        label: "Nitelikli başvuru",
        previous: "9",
        current: "14",
        change: "+%56",
      },
      {
        label: "Tahmini hacim",
        previous: "1.800 adet",
        current: "3.100 adet",
        change: "+%72",
      },
    ],
    rationale:
      "Başvuru sayısı ve beyan edilen hacim aynı dönemde birlikte yükseldi.",
    history: history(
      "B2B talepleri çözüm ve işletme türüne göre gruplandı.",
      "9 Ağustos 2026 14:10",
    ),
  },
  {
    ...base,
    id: 7,
    title: "İzmir’de uyku kategorisi büyüme fırsatı",
    description:
      "İzmir siparişlerinde uyku kategorisi payı genel ortalamanın üzerinde seyrediyor.",
    source: "Satışlar",
    type: "Büyüme Önerisi",
    priority: "Orta",
    status: "Yeni",
    detectedAt: "2026-08-07T12:30:00+03:00",
    channel: "Web sitesi",
    affectedArea: "İzmir · Uyku kategorisi",
    metricLabel: "Kategori büyümesi",
    metricValue: "%24",
    changePercent: 24,
    trendImpact: "positive",
    financialImpact: 88000,
    periodComparison: "Son 90 gün / önceki 90 gün",
    recommendation:
      "İzmir hedefli uyku kategorisi içerik ve kampanya testi yapın.",
    expectedImpact: "Bölgesel talep daha verimli değerlendirilebilir.",
    suggestedTeam: "Pazarlama",
    evidence: [
      {
        label: "Kategori satışı",
        previous: "₺318 bin",
        current: "₺394 bin",
        change: "+%24",
      },
      {
        label: "Bölgesel pay",
        previous: "%12",
        current: "%16",
        change: "+4 puan",
      },
    ],
    rationale: "Bölgesel büyüme hem ciroda hem kategori payında gözlendi.",
    history: history(
      "Şehir ve kategori kırılımı incelendi.",
      "7 Ağustos 2026 12:30",
    ),
  },
  {
    ...base,
    id: 8,
    title: "E-arşiv hatası nedeniyle faturalar bekliyor",
    description:
      "Fatura entegrasyonundaki hata yeni belgelerin işlenmesini geciktiriyor.",
    source: "Entegrasyonlar",
    type: "Operasyon Uyarısı",
    priority: "Kritik",
    status: "İnceleniyor",
    detectedAt: "2026-08-06T08:50:00+03:00",
    channel: "Tüm kanallar",
    affectedArea: "E-Arşiv Fatura Altyapısı",
    metricLabel: "Bekleyen fatura",
    metricValue: "24 kayıt",
    changePercent: 140,
    trendImpact: "negative",
    financialImpact: 212000,
    periodComparison: "Son 24 saat / önceki 24 saat",
    recommendation:
      "Bekleyen faturaları önceliklendirin ve bağlantı yapılandırmasını kontrol edin.",
    expectedImpact: "Fatura gecikmeleri ve operasyon yükü azaltılabilir.",
    suggestedTeam: "Finans ve Operasyon",
    targetDuration: "1 gün",
    evidence: [
      {
        label: "Bekleyen fatura",
        previous: "10",
        current: "24",
        change: "+%140",
      },
      { label: "Hatalı işlem", previous: "2", current: "8", change: "+%300" },
    ],
    rationale: "Bekleyen ve hatalı işlem sayıları eşzamanlı yükseldi.",
    history: history(
      "Entegrasyon işlem kayıtları kontrol edildi.",
      "6 Ağustos 2026 08:50",
    ),
  },
  {
    ...base,
    id: 9,
    title: "Yüksek sepetli siparişlerde iptal artışı",
    description:
      "₺3.000 üzeri sepetlerde ödeme sonrası iptal oranı belirgin biçimde yükseldi.",
    source: "İade ve iptaller",
    type: "Anomali",
    priority: "Yüksek",
    status: "Aksiyon Planlandı",
    detectedAt: "2026-08-04T15:35:00+03:00",
    channel: "Web sitesi",
    affectedArea: "₺3.000 üzeri siparişler",
    metricLabel: "İptal oranı",
    metricValue: "%6,7",
    changePercent: 48,
    trendImpact: "negative",
    financialImpact: 164000,
    periodComparison: "Son 30 gün / önceki 30 gün",
    recommendation:
      "İptal gerekçelerini teslimat süresi ve ödeme yöntemi kırılımında doğrulayın.",
    expectedImpact: "Yüksek değerli sipariş kaybı azaltılabilir.",
    suggestedTeam: "Müşteri Deneyimi",
    evidence: [
      {
        label: "İptal oranı",
        previous: "%4,5",
        current: "%6,7",
        change: "+%48",
      },
      {
        label: "İptal cirosu",
        previous: "₺112 bin",
        current: "₺164 bin",
        change: "+%46",
      },
    ],
    rationale: "Oran ve kaybedilen ciro aynı yönde yükseldi.",
    actionPlan: {
      team: "Müşteri Deneyimi",
      targetDate: "2026-08-28",
      description: "İptal görüşmelerini neden kodlarıyla sınıflandırma.",
    },
    history: history(
      "Yüksek sepet kohortu karşılaştırıldı.",
      "4 Ağustos 2026 15:35",
    ),
  },
  {
    ...base,
    id: 10,
    title: "Ofis koleksiyonunda çapraz satış fırsatı",
    description:
      "Office Collection alan müşteriler Employee Welcome Kits ürünlerine de ilgi gösteriyor.",
    source: "Ürünler",
    type: "Fırsat",
    priority: "Düşük",
    status: "Yeni",
    detectedAt: "2026-07-28T10:00:00+03:00",
    channel: "B2B",
    affectedArea: "Office Collection",
    metricLabel: "Birlikte görüntülenme",
    metricValue: "%41",
    changePercent: 19,
    trendImpact: "positive",
    financialImpact: 61000,
    periodComparison: "Son 90 gün / önceki 90 gün",
    recommendation:
      "İki çözümü birlikte sunan kurumsal paket varyantını test edin.",
    expectedImpact: "Ortalama proje tutarında artış fırsatı olabilir.",
    suggestedTeam: "B2B Satış",
    evidence: [
      {
        label: "Birlikte görüntülenme",
        previous: "%34",
        current: "%41",
        change: "+7 puan",
      },
    ],
    rationale: "Aynı oturum ve başvurularda iki çözüm sık birlikte görülüyor.",
    history: history("Ürün ilgi ilişkileri incelendi.", "28 Temmuz 2026 10:00"),
  },
  {
    ...base,
    id: 11,
    title: "Stok uyarı eşiği iyileştirildi",
    description:
      "Kritik ürünlerde yeni uyarı eşiği uygulandı ve gecikmeler azaldı.",
    source: "Stok",
    type: "Operasyon Uyarısı",
    priority: "Orta",
    status: "Çözüldü",
    detectedAt: "2026-07-20T09:00:00+03:00",
    resolvedAt: "2026-08-03T16:00:00+03:00",
    channel: "Tüm kanallar",
    affectedArea: "Kritik stok grubu",
    metricLabel: "Geciken yenileme",
    metricValue: "3 ürün",
    changePercent: -57,
    trendImpact: "positive",
    financialImpact: 0,
    periodComparison: "Uygulama öncesi / sonrası",
    recommendation: "Yeni eşikleri aylık olarak yeniden değerlendirin.",
    expectedImpact: "Stok kesintisi riski daha erken görülebilir.",
    suggestedTeam: "Tedarik ve Stok",
    evidence: [
      {
        label: "Geciken yenileme",
        previous: "7 ürün",
        current: "3 ürün",
        change: "-%57",
      },
    ],
    rationale: "Yeni eşik sonrasında gecikmiş yenileme sayısı düştü.",
    history: [
      ...history("Stok gecikmeleri analiz edildi.", "20 Temmuz 2026 09:00"),
      {
        title: "Çözüldü",
        description: "Yeni eşikler uygulandı.",
        date: "3 Ağustos 2026 16:00",
      },
    ],
  },
  {
    ...base,
    id: 12,
    title: "Düşük hacimli sosyal kanal sinyali",
    description:
      "Sosyal yönlendirmeler artıyor ancak veri hacmi karar için henüz sınırlı.",
    source: "Satışlar",
    type: "Büyüme Önerisi",
    priority: "Düşük",
    status: "Göz Ardı Edildi",
    detectedAt: "2026-07-18T11:00:00+03:00",
    channel: "Web sitesi",
    affectedArea: "Sosyal yönlendirme",
    metricLabel: "Yönlendirilen oturum",
    metricValue: "640",
    changePercent: 12,
    trendImpact: "neutral",
    financialImpact: 18000,
    periodComparison: "Son 30 gün / önceki 30 gün",
    recommendation: "Daha geniş örneklem oluşana kadar eğilimi izleyin.",
    expectedImpact:
      "Yeni kanal fırsatı daha güvenilir veriyle değerlendirilebilir.",
    suggestedTeam: "Pazarlama",
    evidence: [
      { label: "Oturum", previous: "571", current: "640", change: "+%12" },
    ],
    rationale:
      "Pozitif sinyal var ancak dönüşüm sayısı istatistiksel olarak sınırlı.",
    history: [
      ...history("Sosyal trafik incelendi.", "18 Temmuz 2026 11:00"),
      {
        title: "Göz ardı edildi",
        description: "Daha fazla veri bekleniyor.",
        date: "19 Temmuz 2026 10:20",
      },
    ],
  },
];

export const reviewThemes: ReviewTheme[] = [
  {
    id: 1,
    title: "Ambalaj dayanıklılığı",
    area: "Banyo ve mutfak",
    reviewCount: 46,
    sentiment: "Olumsuz",
    changePercent: 35,
    summary: "Kutu deformasyonu ve yetersiz iç koruma temaları tekrar ediyor.",
    recommendation: "Köşe koruyucu ve darbe emici iç malzeme pilotu.",
  },
  {
    id: 2,
    title: "Koku kalıcılığı",
    area: "Oda kokuları",
    reviewCount: 32,
    sentiment: "Olumlu",
    changePercent: 18,
    summary: "Kalıcılık ve dengeli yoğunluk olumlu biçimde öne çıkıyor.",
    recommendation:
      "Ürün sayfasında doğrulanmış kullanım deneyimini vurgulama.",
  },
  {
    id: 3,
    title: "Kapak kullanım kolaylığı",
    area: "Saklama ürünleri",
    reviewCount: 21,
    sentiment: "Olumsuz",
    changePercent: 11,
    summary: "İlk kullanımda kapağın sert olduğu yönünde ortak tema oluştu.",
    recommendation: "Açma kuvveti testi ve kullanım görseli iyileştirmesi.",
  },
];
